# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [38]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import gkey

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [39]:
weather_data = pd.read_csv("../output_data/weather_data.csv")
weather_data.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Palana,99,RU,1582168711,88,59.12,159.97,-6.25,0.98
1,1,Vaini,20,TO,1582168711,65,-21.20,-175.20,82.40,10.29
2,2,Ushuaia,90,AR,1582168696,87,-54.80,-68.30,48.20,24.16
3,3,Dwarka,0,IN,1582168712,71,22.24,68.97,74.73,10.80
4,4,Cooma,0,AU,1582168712,48,-36.23,149.13,60.80,10.29

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [40]:
gmaps.configure(api_key=gkey)

locations = weather_data[["Lat","Lng"]]

humidity_map = gmaps.figure()
heatmap_layer = gmaps.heatmap_layer(locations,
                                    weights=weather_data["Humidity"],
                                    dissipating=False, 
                                    max_intensity=250,
                                    point_radius=4)
humidity_map.add_layer(heatmap_layer)
humidity_map

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [41]:
#Ideal conditions:
# A max temperature lower than 80 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.
ideal = weather_data.loc[(weather_data["Max Temp"] < 80) & (weather_data["Max Temp"] > 70),:]
ideal = ideal.loc[ideal["Wind Speed"] < 10,:]
ideal = ideal.loc[ideal["Cloudiness"] == 0,:]
ideal.count()

Unnamed: 0    21
City          21
Cloudiness    21
Country       21
Date          21
Humidity      21
Lat           21
Lng           21
Max Temp      21
Wind Speed    21
dtype: int64

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [42]:
hotel_df = ideal
hotel_df["Hotel Name"] = ""
#hotel_df

In [43]:
# Set params and base_url for nearby search
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {"key":gkey,
         "location":"",
         "radius":5000,
         "keyword":"hotel",
         "type":"hotel"}

# Call API and store hotel name into dataframe
for index,row in hotel_df.iterrows():
    params["location"] = str(row["Lat"]) + "," + str(row["Lng"])
    response = requests.get(base_url,params=params)
    #if response.status_code() == 200:
    results = response.json()["results"]
    print(f"Working on {row['City']}")
    try:
          hotel_df.loc[index,"Hotel Name"] = results[0]["name"]
    except IndexError:
          print(f"No hotels found within 5 kilometers of {row['City']}.")

hotel_df

Working on Sittwe
Working on Varangaon
No hotels found within 5 kilometers of Varangaon.
Working on Emilio Carranza
Working on Tomatlan
Working on Zarate
Working on Vega de Alatorre
Working on Maymyo
Working on Bongandanga
No hotels found within 5 kilometers of Bongandanga.
Working on Chokwe
Working on Galle
Working on Rafaela
Working on Ghugus
No hotels found within 5 kilometers of Ghugus.
Working on Koraput
Working on Presidencia Roque Saenz Pena
Working on Santiago
Working on Avanigadda
No hotels found within 5 kilometers of Avanigadda.
Working on Gualeguaychu
Working on Kpandae
No hotels found within 5 kilometers of Kpandae.
Working on Batemans Bay
Working on Nikki
Working on Matara

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
53,53,Sittwe,0,MM,1582168723,60,20.15,92.90,70.14,2.30,Shwe Thazin Hotel
93,93,Varangaon,0,IN,1582168731,25,21.02,75.90,74.17,5.46,
101,101,Emilio Carranza,0,MX,1582168733,85,19.97,-96.61,74.79,3.49,Hotel Marea Baja
107,107,Tomatlan,0,MX,1582168734,75,19.93,-105.25,70.36,1.95,Hotel Misión San Miguel
202,202,Zarate,0,AR,1582168576,68,-34.10,-59.03,72.00,2.24,Kin Hotel
214,214,Vega de Alatorre,0,MX,1582168758,85,20.03,-96.63,74.79,3.49,Hotel Dorado
231,231,Maymyo,0,MM,1582168761,37,22.03,96.47,71.60,8.05,Aureum Palace Hotel & Resort Pyin Oo Lwin
248,248,Bongandanga,0,CD,1582168765,97,1.50,21.05,70.14,2.53,
296,296,Chokwe,0,MZ,1582168774,94,-24.53,32.98,73.38,5.06,Complexo Sonho Real
348,348,Galle,0,LK,1582168784,81,6.04,80.22,77.25,5.26,Amari Galle Sri Lanka
362,362,Rafaela,0,AR,1582168651,52,-31.25,-61.49,72.00,2.98,Amérian Rafaela Hotel
382,382,Ghugus,0,IN,1582168791,68,19.93,79.13,74.39,9.78,
413,413,Koraput,0,IN,1582168688,66,18.82,82.72,71.80,4.36,Raj Residency
423,423,Presidencia Roque Saenz Pena,0,AR,1582168799,55,-26.79,-60.44,71.85,3.58,Hotel Gualok
427,427,Santiago,0,CL,1582168800,43,-33.46,-70.65,71.60,6.93,Hotel ibis Santiago Estacion Central
514,514,Avanigadda,0,IN,1582168817,83,16.02,80.92,73.40,7.74,
515,515,Gualeguaychu,0,AR,1582168817,68,-33.01,-58.52,71.01,4.00,Placeres de la Costa
525,525,Kpandae,0,GH,1582168683,56,8.47,-0.01,76.86,4.27,
538,538,Batemans Bay,0,AU,1582168822,62,-35.72,150.18,73.00,5.99,Bay Breeze Motel
569,569,Nikki,0,BJ,1582168828,18,9.94,3.21,70.18,5.79,Hotel John
577,577,Matara,0,LK,1582168796,64,5.95,80.54,79.79,4.92,Amaloh Boutique Resort

In [44]:
# Narrow dataframe to cities with hotels within 5km
narrowed_city_df = hotel_df.loc[hotel_df["Hotel Name"] != "",:]
narrowed_city_df.count()

Unnamed: 0    16
City          16
Cloudiness    16
Country       16
Date          16
Humidity      16
Lat           16
Lng           16
Max Temp      16
Wind Speed    16
Hotel Name    16
dtype: int64

In [45]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = narrowed_city_df[["Lat", "Lng"]]

In [46]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations,info_box_content=hotel_info)
humidity_map.add_layer(markers)
# Display Map
humidity_map

Figure(layout=FigureLayout(height='420px'))